name: Render and Deploy Quarto Book

on:
  push:
    branches:
      - main  

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R packages
        run: Rscript -e "packages <- c('dplyr','tidyr','ggplot2','MASS','MCMCpack'); \
                   new <- packages[!(packages %in% installed.packages()[,'Package'])]; \
                   if(length(new)) install.packages(new)"
        
      - name: Render Quarto book
        run: quarto render
        
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Output
